FROM nginx:1.12-alpine-perl

LABEL maintainer="Manish Kumar <rishimanish123@gmail.com>"

ARG TIMEZONE
RUN apk update && apk add --no-cache --virtual .build-deps tzdata && \
    ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && \
    echo $TIMEZONE > /etc/timezone && \
    apk del .build-deps
ENV TZ $TIMEZONE

RUN rm /etc/nginx/conf.d/default.conf 

COPY nginx.conf /etc/nginx
    
